clustering yaml creayed
DendrouLab/panpipes pull request #202
Opened 2024-02-28 10:43 UTC by giuliaelgarcia

Created clustering yaml file. 
Please check line 267 for default and check formating from line 140 onwards (when there are 2 default values)

2024-02-28 13:30 UTC, bio-la requested changes
please pull again the branch (i've added some fixes) and check my comments.
I've added the file to the index so you can see the documentation rendered and check how the structure looks.
please be careful with spelling typos

2024-02-28 13:30 UTC, bio-la commented on docs/yaml_docs/pipeline_clustering_yml.md
> +       If the number of clusters contains less than the number of cells maker analysis is not necessary.
i don't understand this, please check the documentation of scanpy.rank_genes to explain this parameter

2024-02-28 13:30 UTC, bio-la commented on docs/yaml_docs/pipeline_clustering_yml.md
> +       This parameter only matters if pseudo_seurat is set to True
check my previous corrections "this parameter is mandatory if..."

2024-03-06 15:42 UTC, bio-la reviewed
please spell check!

2024-03-06 15:42 UTC, bio-la commented on docs/yaml_docs/pipeline_clustering_yml.md
>         If the number of clusters contains less than the number of cells maker analysis is not necessary.
Min number of cells in a cluster. If the cluster contains less than this number of cells, the marker analysis won't be run.

2024-03-26 09:54 UTC, deevdevil88 commented on docs/yaml_docs/pipeline_clustering_yml.md
> +       Minimal number of cells in a cluster. If the cluster contains less than this number of cells, the marker analysis won't be run.
I would say " Marker analysis  is run for clusters  >= mincells. If a cluster ncells < mincells , then the cluster is excluded from marker analysis

2024-03-26 09:55 UTC, deevdevil88 commented on docs/yaml_docs/pipeline_clustering_yml.md
> +       - <span class="parameter">mincels </span> `Integer`, Default: 10<br>
type change to mincells

2024-03-26 09:56 UTC, deevdevil88 commented on docs/yaml_docs/pipeline_clustering_yml.md
> +   - <span class="parameter">mincels </span> `Integer`, Default: 10<br>
typo it should be mincells

2024-03-26 09:57 UTC, deevdevil88 commented on docs/yaml_docs/pipeline_clustering_yml.md
> +    - <span class="parameter">mincels </span> `Integer`, Default: 10<br>
typo and change expalnaation as above

2024-03-26 09:57 UTC, deevdevil88 commented on docs/yaml_docs/pipeline_clustering_yml.md
> +   - <span class="parameter">mincels </span> `Integer`, Default:10<br>
typo and explanantion change

2024-03-26 09:57 UTC, deevdevil88 commented on docs/yaml_docs/pipeline_clustering_yml.md
> +   - <span class="parameter">mincels </span> `Integer`, Default: 10<br>
typo and expalantion change

2024-03-26 09:58 UTC, deevdevil88 requested changes
some typose and  mincells explanation needs to be changed

2024-04-24 14:52 UTC, bio-la reviewed
- clarified modalities
- removed wrong parameters

2024-04-24 15:13 UTC, bio-la approved these changes

2024-04-24 16:32 UTC, deevdevil88 approved these changes

2024-04-26 09:44 UTC, merged