Improve logging
DendrouLab/panpipes pull request #246
Opened 2024-03-26 14:27 UTC by SarahOuologuem

Hi! I added some logging to the spatial workflows and wanted to check with you @bio-la whether this is what you're thinking of before I continue with the other workflows.

2024-03-27 08:27 UTC, bio-la reviewed
these look good checkpoint messages to me!

2024-04-19 14:15 UTC, bio-la requested changes

2024-04-19 14:15 UTC, bio-la commented on panpipes/python_scripts/batch_correct_bbknn.py
> -L.info("preparing for integration")
put this line back please

2024-04-19 14:15 UTC, bio-la commented on panpipes/python_scripts/batch_correct_harmony.py
> +L.info(args)
I prefer the vesion of this command with a preamble "running with params"

2024-04-22 10:12 UTC, SarahOuologuem commented on panpipes/python_scripts/batch_correct_bbknn.py
> -L.info("Running with options: %s", args)
ok! would you also add the script to the log, i.e.` L.info(os.path.basename(__file__))`?

2024-04-26 08:48 UTC, SarahOuologuem commented on panpipes/panpipes/pipeline_clustering.py
> +           r"logs/8_find_markers_\1_\2_\3.log",
it looks like this
![clustering_logs](https://github.com/DendrouLab/panpipes/assets/68101181/b08bc7ba-769c-49d0-9986-173e8f140175)

2024-04-26 08:48 UTC, SarahOuologuem commented on panpipes/python_scripts/batch_correct_bbknn.py
> -L.info("preparing for integration")
done

2024-04-26 08:50 UTC, SarahOuologuem commented
@bio-la  I now added 
`L.info("Running with params: %s", args)` to every file instead of `L.info(args)`

2024-04-27 12:50 UTC, bio-la approved these changes

2024-04-27 12:50 UTC, merged

2024-04-27 12:50 UTC, bio-la commented
@SarahOuologuem awesome job!