Create pipeline_refmap_yml.md
DendrouLab/panpipes pull request #250
Opened 2024-04-08 14:43 UTC by giuliaelgarcia

Created the refmap yaml documentation

2024-04-23 09:22 UTC, deevdevil88 commented
@bio-la  can you  also eview the refmap one please after i am done . As i havent used this workflow a lot  and done refmapping outside panpipes, i might miss something.

2024-04-23 09:23 UTC, deevdevil88 commented on docs/yaml_docs/pipeline_refmap_yml.md
> +  	    Number of threads used for low intensity computing tasks.
the space indent doesnt match the lines above. please change

2024-04-23 09:29 UTC, deevdevil88 requested changes
just one space indent change but other looks ok to me @giuliaelgarcia

2024-04-23 09:40 UTC, deevdevil88 commented on docs/yaml_docs/pipeline_refmap_yml.md
> +- <span class="parameter">sacnvi</span> `String`, Default:path/to/scanvi<br>
typo, should scanvi

2024-04-23 09:41 UTC, deevdevil88 commented on docs/yaml_docs/pipeline_refmap_yml.md
> +- <span class="parameter">impute_proteins</span> `Boolean`, Default: True<br> CHEEEEECKKKKKK
@bio-la  we werent sure if this is meant to True or False by default

2024-04-23 09:43 UTC, deevdevil88 requested changes
some typos need fixing

2024-04-24 09:38 UTC, bio-la approved these changes

2024-04-24 09:39 UTC, bio-la approved these changes

2024-04-25 10:35 UTC, deevdevil88 approved these changes

2024-04-25 15:25 UTC, merged